<?php
namespace Ferret\Detector;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for Pathinfo.
 * Generated by PHPUnit on 2010-10-09 at 20:06:58.
 */
class PathinfoTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Pathinfo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Pathinfo;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testDetect().
     */
    public function testDetect()
    {
      $this->assertEquals('text/plain', $this->object->detect('data/unitzzz.txt'));
      
    }
    
    /**
     * @todo Implement testDetect().
     */
    public function testDetectFail()
    {
      $this->assertFalse($this->object->detect('data/unit.false'));
      
    }    
}
?>
